[package]
name = "file-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
glob = "0.3.0"
itertools = "0.10.1"
termion = "1.5.6"
tui = "0.16.0"
